[workspace]
resolver = "2"
members = [
    "crates/borer-core",
    "crates/borer-client",
    "crates/borer-server",
]

[workspace.dependencies]
tokio = { version = "1.48.0", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
thiserror = "2.0.17"