[package]
name = "borerd"
version = "0.1.0"
edition = "2024"


[dependencies]
borer-core = { path = "../borer-core" }
axum = { version = "0.8.8", features = ["ws"] }
tokio = { workspace = true }
futures = "0.3.31"

